// === ABM DASHBOARD v4.0 — AUTO-GENERATED DATA ===
// Generated: 2026-03-15 07:50:00
// Script: dashboard/sync.ps1 v4.0
// KHÔNG SỬA TAY — chạy: powershell dashboard/sync.ps1

const TASK_DATA = [
    {id:"TASK-001",date:"2026-03-08",title:"Publish ABM Workforce lên GitHub",department:"Ban Giám Đốc",agent:"Jarvis",worker:"dev-worker",skills:["git-worktrees"],status:"done",completion:100,result:"Repo xaotiensinh-abm/abm-workforce published thành công",description:"Khởi tạo repository GitHub cho toàn bộ hệ thống ABM Workforce. Setup .gitignore, README ban đầu, push toàn bộ codebase lên remote.",files_changed:["README.md",".gitignore","_abm/"],decisions:["Dùng public repo để community có thể tham khảo","Main branch strategy"],evidence:"git push origin main → success. Repo live tại github.com/xaotiensinh-abm/abm-workforce",session_id:"SESSION-001",duration:30},
    {id:"TASK-002",date:"2026-03-09",title:"Mô hình Doanh Nghiệp Số — 9 phòng ban",department:"Ban Giám Đốc",agent:"Jarvis",worker:"business-analyst",skills:["writing-plans","brainstorming"],status:"done",completion:100,result:"9 phòng ban mapped đầy đủ, 6 skills Văn Phòng Số",description:"Thiết kế mô hình doanh nghiệp số cho ABM: 9 phòng ban, mỗi phòng được mapping skills + agent tương ứng.",files_changed:["_abm/bmm/agents/jarvis-orchestrator.md","_abm/_config/skill-manifest.csv"],decisions:["9 phòng ban thay vì 6 như enterprise truyền thống","Mỗi phòng có agent + skills riêng"],evidence:"9 departments mapped với routing table trong jarvis-orchestrator.md",session_id:"SESSION-001",duration:60},
    {id:"TASK-003",date:"2026-03-09",title:"Review đa chiều v2.4 — 10 chiều + 8 personas",department:"Ban Giám Đốc",agent:"Jarvis",worker:"jarvis-direct",skills:["multi-dimensional-review","critical-thinking"],status:"done",completion:100,result:"Điểm 8.33/10 — phát hiện 4 issues, fix toàn bộ",description:"Audit toàn diện hệ thống ABM v2.4 với 10 chiều đánh giá và 8 personas phản biện (Hacker, Auditor, CEO, Architect, Pragmatist, Competitor, Operator, New Hire).",files_changed:["_abm-output/audit-v2.4.md"],decisions:["Chuẩn hóa 10 chiều đánh giá thành template cố định","8 personas phản biện mandatory"],evidence:"Điểm 8.33/10. 4 issues P0-P1 phát hiện và fix trong cùng phiên.",session_id:"SESSION-001",duration:45},
    {id:"TASK-004",date:"2026-03-09",title:"Email Sandbox Mode + Fallback Routing",department:"IT — Công Nghệ",agent:"Jarvis",worker:"dev-worker",skills:["agent-email-cli","writing-plans"],status:"done",completion:100,result:"Sandbox BẬT mặc định, 23 routes",description:"Cài đặt chế độ sandbox cho email agent, đảm bảo KHÔNG gửi email thật khi test. Fallback routing xử lý trường hợp không match task_type.",files_changed:["_abm/bmm/agents/skills/agent-email-cli/SKILL.md"],decisions:["Sandbox BẬT mặc định — an toàn trước hiệu suất","23 routes fallback"],evidence:"66/66 email routes KHÔNG sử dụng gửi thật. Sandbox mode hoạt động.",session_id:"SESSION-001",duration:35},
    {id:"TASK-005",date:"2026-03-09",title:"Health Check Script + FAQ + CI/CD",department:"IT — Công Nghệ",agent:"Jarvis",worker:"dev-worker",skills:["systematic-debugging","writing-plans"],status:"done",completion:100,result:"health-check.ps1 PASS 16/16, FAQ.md 10 questions",description:"Tạo script kiểm tra sức khỏe hệ thống: verify skills, workflows, agents, config. Viết FAQ 10 câu hỏi thường gặp. Setup CI/CD verify workflow.",files_changed:["health-check.ps1","FAQ.md",".github/workflows/verify.yml"],decisions:["PowerShell script cho cross-platform support","16 checks bao phủ mọi thành phần"],evidence:"health-check.ps1 PASS 16/16 tests. FAQ.md 10 Q&A pairs.",session_id:"SESSION-001",duration:40},
    {id:"TASK-006",date:"2026-03-09",title:"Phân tích Brand Guideline abmedu.vn",department:"Marketing",agent:"Jarvis",worker:"marketing-specialist",skills:["product-marketing-context","deep-research"],status:"done",completion:100,result:"brand-guideline-abmedu.yaml: 6 colors, Montserrat, logo",description:"Deep research website abmedu.vn, extract brand identity: color palette, typography, tone of voice, logo usage. Tạo brand guideline YAML cho toàn hệ thống.",files_changed:["_abm/Context-Layer/Second-Brain/standards/brand-guideline-abmedu.yaml"],decisions:["YAML format thay vì JSON — dễ đọc hơn cho non-dev","6 màu chính extracted"],evidence:"brand-guideline-abmedu.yaml hoàn chỉnh. Logo 320px extracted từ abmedu.vn.",session_id:"SESSION-001",duration:30},
    {id:"TASK-007",date:"2026-03-10",title:"10 Bài Viết Marketing — 16 Bài Giảng AI",department:"Marketing",agent:"Jarvis",worker:"marketing-specialist",skills:["copywriting","content-strategy","social-content","email-marketing"],status:"done",completion:100,result:"10 bài đa nền tảng: FB, IG, TikTok, LinkedIn, Zalo, Email",description:"Viết 10 bài marketing cho 16 bài giảng AI, tối ưu cho từng nền tảng: Facebook, Instagram, TikTok, LinkedIn, Zalo, Email.",files_changed:["_abm-output/marketing/10-bai-viet-marketing.md"],decisions:["Mỗi bài viết customize cho nền tảng riêng","Hook → Pain → Solution → CTA framework"],evidence:"10 bài viết hoàn chỉnh, multi-platform format. 1.200K+ estimated reach.",session_id:"SESSION-001",duration:90},
    {id:"TASK-008",date:"2026-03-10",title:"BMAD Upgrade — 5 skills + creative-strategist + /council",department:"Ban Giám Đốc",agent:"Jarvis",worker:"dev-worker",skills:["writing-plans","skill-creator"],status:"done",completion:100,result:"v2.6: project-hierarchy, sprint-planning, critical-thinking",description:"Nâng cấp ABM lên v2.6: thêm 5 skills mới, tạo creative-strategist agent, và /council workflow cho multi-agent review.",files_changed:["_abm/bmm/agents/skills/project-hierarchy/","_abm/bmm/agents/skills/critical-thinking/",".agents/workflows/council.md"],decisions:["critical-thinking là mandatory cho tất cả reviews","/council dùng multi-agent consolidate + ranking"],evidence:"v2.6 verified: 5 skills hoạt động, /council workflow tested.",session_id:"SESSION-001",duration:60},
    {id:"TASK-009",date:"2026-03-10",title:"Wave 1+2 — Self-healing, MCP, Vận Hành, Pháp Chế",department:"Ban Giám Đốc",agent:"Jarvis",worker:"dev-worker",skills:["writing-plans","skill-creator"],status:"done",completion:100,result:"v2.7: 7 skills mới. 78→80 total. 30 routes.",description:"2 đợt nâng cấp: Wave 1 (Self-healing, MCP, context engineering), Wave 2 (skills Vận Hành + Pháp Chế).",files_changed:["_abm/bmm/agents/skills/supply-chain/","_abm/bmm/agents/skills/contract-review/"],decisions:["Chia 2 wave để kiểm soát rủi ro","Vận Hành + Pháp Chế ưu tiên vì thiếu coverage"],evidence:"78→80 skills. 30 routes. Không break existing.",session_id:"SESSION-001",duration:75},
    {id:"TASK-010",date:"2026-03-10",title:"Review v2.7 — Audit phản biện",department:"Ban Giám Đốc",agent:"Jarvis",worker:"jarvis-direct",skills:["multi-dimensional-review","critical-thinking"],status:"done",completion:100,result:"9.35/10 — 8 personas: 9/10 consensus. 0 red, 2 yellow.",description:"Full audit v2.7: 10 chiều đánh giá + 8 personas phản biện. 0 lỗi nghiêm trọng, 2 cảnh báo nhẹ.",files_changed:["_abm-output/audit-v2.7.md"],decisions:["2 yellow warnings acceptable","Tiếp tục nâng cấp phòng ban yếu"],evidence:"9.35/10. 8/8 personas đồng thuận. 0 red flags.",session_id:"SESSION-001",duration:40},
    {id:"TASK-011",date:"2026-03-11",title:"Web Dashboard ABM v2.7",department:"IT — Công Nghệ",agent:"Jarvis",worker:"dev-worker",skills:["frontend-design","ui-ux-pro-max"],status:"done",completion:100,result:"dashboard/index.html: dark theme, 9 phòng ban, scoring",description:"Xây dựng dashboard web premium. Dark theme, hiển thị phòng ban, scoring audit, health status, task table, analytics charts.",files_changed:["dashboard/index.html","dashboard/task-data.js","dashboard/sync.ps1"],decisions:["Single HTML file — không cần build tool","Dark theme — phù hợp CEO","Auto-refresh 30s"],evidence:"Dashboard render đúng, stats, charts. File:// protocol hoạt động.",session_id:"SESSION-002",duration:120},
    {id:"TASK-012",date:"2026-03-11",title:"Fix P1+P2: CHANGELOG + Vận Hành + Quick Start",department:"Ban Giám Đốc",agent:"Jarvis",worker:"dev-worker",skills:["writing-plans","skill-creator"],status:"done",completion:100,result:"ABM-CHANGELOG.md, inventory-management, QUICK-START.md",description:"Fix sau audit: tạo CHANGELOG.md, thêm skills inventory-management + logistics-optimization, viết QUICK-START.md 5 phút.",files_changed:["ABM-CHANGELOG.md","QUICK-START.md","_abm/bmm/agents/skills/inventory-management/"],decisions:["CHANGELOG dùng Keep a Changelog standard","Quick Start 5 bước dưới 5 phút"],evidence:"3 files tạo thành công. CHANGELOG ghi đầy đủ v2.0→v2.7.",session_id:"SESSION-002",duration:45},
    {id:"TASK-013",date:"2026-03-11",title:"Marketing Upgrade — 11 skills từ coreyhaines31",department:"Marketing",agent:"Jarvis",worker:"dev-worker",skills:["ad-creative","ai-seo","analytics-tracking","email-sequence","referral-program","free-tool-strategy","copy-editing","programmatic-seo","signup-flow-cro","form-cro","popup-cro"],status:"done",completion:100,result:"v2.8: 91 skills, 34 routes. Marketing dẫn đầu.",description:"Tích hợp 11 skills marketing từ coreyhaines31/marketingskills: CRO, SEO, Growth, Content, Analytics.",files_changed:["_abm/bmm/agents/skills/ad-creative/","_abm/bmm/agents/skills/ai-seo/"],decisions:["Adopt 11/11 skills — quality cao","Marketing phòng ban dẫn đầu: 16→27 skills"],evidence:"v2.8: 91 skills verified, 34 routes. Tất cả SKILL.md đúng format.",session_id:"SESSION-002",duration:60},
    {id:"TASK-014",date:"2026-03-11",title:"Review v2.8 — Audit + Phương án bổ sung",department:"Ban Giám Đốc",agent:"Jarvis",worker:"jarvis-direct",skills:["multi-dimensional-review","critical-thinking"],status:"done",completion:100,result:"9.58/10 — P0: cân bằng 5 phòng ban yếu (+12 skills)",description:"Audit v2.8 phát hiện mất cân bằng: Marketing 27 skills, trong khi HR/KT/PC/CSKH/VH chỉ 1-2 skills. Đề xuất bổ sung 12 skills.",files_changed:["_abm-output/audit-v2.8.md"],decisions:["P0: Cân bằng 5 phòng ban yếu là ưu tiên số 1","Mỗi phòng cần tối thiểu 4-7 skills"],evidence:"9.58/10. Phát hiện imbalance. Kế hoạch +12 skills được CEO approve.",session_id:"SESSION-002",duration:35},
    {id:"TASK-015",date:"2026-03-11",title:"Cân bằng 5 Phòng Ban — 12 skills mới",department:"Ban Giám Đốc",agent:"Jarvis",worker:"dev-worker",skills:["performance-review","employee-engagement","talent-acquisition","expense-management","cash-flow-forecast","tax-compliance","ip-protection","labor-law","quality-management","facility-management","ticket-management","customer-feedback"],status:"done",completion:100,result:"v2.9: 103 skills, 39 routes. HR 7, KT 7, PC 4, VH 5.",description:"Thêm 12 skills cho 5 phòng ban yếu: HR (+3), Kế Toán (+3), Pháp Chế (+2), Vận Hành (+2), CSKH (+2).",files_changed:["_abm/bmm/agents/skills/performance-review/","_abm/bmm/agents/skills/expense-management/"],decisions:["Phân bổ 12 skills theo tỷ lệ cân bằng","Ưu tiên skills có business impact cao"],evidence:"v2.9: 103 skills verified. HR 7, KT 7, PC 4, VH 5, CSKH 5.",session_id:"SESSION-002",duration:90},
    {id:"TASK-016",date:"2026-03-12",title:"Phòng Đào Tạo — 6 skills + SubAgent + Workflow",department:"Đào Tạo",agent:"Jarvis",worker:"dev-worker",skills:["course-design","lms-management","student-assessment","training-content","workshop-facilitation","certification-program"],status:"done",completion:100,result:"v3.0: 109 skills. training-specialist SubAgent.",description:"Xây dựng hoàn chỉnh Phòng Đào Tạo: 6 skills chuyên biệt, training-specialist SubAgent, /training workflow.",files_changed:["_abm/bmm/agents/skills/course-design/","_abm/SubAgents/training-specialist.md",".agents/workflows/training.md"],decisions:["training-specialist là SubAgent cấp 2","/training workflow: 5 bước từ khảo sát → đánh giá"],evidence:"v3.0: 109 skills. training-specialist SOUL.md verified.",session_id:"SESSION-002",duration:80},
    {id:"TASK-017",date:"2026-03-12",title:"Audit Phòng Đào Tạo — 9.7/10",department:"Đào Tạo",agent:"Jarvis",worker:"jarvis-direct",skills:["multi-dimensional-review","critical-thinking"],status:"done",completion:100,result:"9.2→9.7/10 sau fix P1",description:"Audit Phòng Đào Tạo. Fix P1: thêm Instructor Management, Gamification, Plagiarism Detection. Điểm 9.2→9.7/10.",files_changed:["_abm-output/audit-dao-tao.md"],decisions:["Gamification quan trọng cho engagement","Plagiarism detection cần cho certification"],evidence:"9.2→9.7/10. 3 P1 fixes applied. 8 personas đồng thuận.",session_id:"SESSION-002",duration:40},
    {id:"TASK-018",date:"2026-03-12",title:"Phòng R&D — 6 skills + RAPID/SQUARE frameworks",department:"R&D",agent:"Jarvis",worker:"dev-worker",skills:["ai-trend-radar","tech-scouting","research-to-training","knowledge-builder","benchmark-lab","innovation-report"],status:"done",completion:100,result:"v3.0: 115 skills. rd-specialist SubAgent.",description:"Xây dựng Phòng R&D: 6 skills, RAPID framework (Research → Assess → Pilot → Integrate → Deploy), SQUARE framework cho benchmark.",files_changed:["_abm/bmm/agents/skills/ai-trend-radar/","_abm/SubAgents/rd-specialist.md"],decisions:["RAPID framework cho nghiên cứu có hệ thống","R&D pipeline: Weekly → Monthly → Quarterly"],evidence:"v3.0: 115 skills. rd-specialist verified. RAPID + SQUARE documented.",session_id:"SESSION-002",duration:90},
    {id:"TASK-019",date:"2026-03-12",title:"Audit Phòng R&D — 9.4/10 + Fix P1",department:"R&D",agent:"Jarvis",worker:"jarvis-direct",skills:["multi-dimensional-review","critical-thinking"],status:"done",completion:100,result:"9.4/10. Fix: budget template, handoff protocol SLA.",description:"Audit Phòng R&D: điểm 9.4/10. Fix P1: budget template, handoff protocol SLA (R&D → Đào Tạo 48h), weekly radar mẫu.",files_changed:["_abm-output/audit-rd.md"],decisions:["Handoff SLA 48h giữa R&D → Đào Tạo","Budget template bắt buộc cho research projects"],evidence:"9.4/10. Budget template và SLA protocol documented.",session_id:"SESSION-002",duration:35},
    {id:"TASK-020",date:"2026-03-12",title:"Community Skills Integration — 5 ADOPT",department:"Đào Tạo",agent:"Jarvis",worker:"dev-worker",skills:["course-design","training-content"],status:"done",completion:100,result:"Curriculum v2: +30h. 112h total.",description:"Tích hợp 5 community skills vào curriculum: Prompt Engineering (6h), RAG (8h), Data Science (4h), AI Agents (12h). Từ 82h lên 112h.",files_changed:["_abm-output/curriculum-v2.md"],decisions:["ADOPT 5/5 skills — quality đạt","Thêm 30h advanced topics"],evidence:"Curriculum v2: 112h total. 5 skills integrated.",session_id:"SESSION-002",duration:45},
    {id:"TASK-021",date:"2026-03-12",title:"AI Trend Radar — Tuần 11/2026",department:"R&D",agent:"Jarvis",worker:"rd-specialist",skills:["ai-trend-radar","tech-scouting"],status:"done",completion:100,result:"HOT: GPT-5.4, Gemini Embedding 2, Luật AI VN",description:"Weekly AI Trend Radar: 3 trends HOT (GPT-5.4, Gemini Embedding 2, Dự thảo Luật AI VN). 7 action items cho ABM.",files_changed:["_abm-output/rd/ai-trend-radar-w11-2026.md"],decisions:["GPT-5.4: Monitor, chưa integrate","Gemini Embedding 2: PILOT cho RAG","Luật AI VN: Legal team review"],evidence:"Radar report w11 published. 3 HOT trends, 7 action items tracked.",session_id:"SESSION-002",duration:50},
    {id:"TASK-022",date:"2026-03-13",title:"Save/Recap System — Session Persistence",department:"IT — Công Nghệ",agent:"Jarvis",worker:"dev-worker",skills:["writing-plans"],status:"done",completion:100,result:"/save + /recap workflows. .abm-sessions/ storage.",description:"Xây dựng hệ thống lưu/khôi phục phiên: /save (10 bước) tạo SESSION file, /recap đọc SESSION + INDEX để khôi phục context.",files_changed:[".agents/workflows/save.md",".agents/workflows/recap.md",".abm-sessions/SESSION-001-2026-03-12.md"],decisions:["Markdown format cho SESSION files","10 bước /save bao gồm sync dashboard"],evidence:"/save tạo SESSION-001 thành công. /recap test đọc được context.",session_id:"SESSION-002",duration:60},
    {id:"TASK-023",date:"2026-03-14",title:"Giáo trình ABM Workforce — Web Training Guide",department:"Đào Tạo",agent:"Jarvis",worker:"dev-worker",skills:["course-design","frontend-design","training-content"],status:"done",completion:100,result:"giao-trinh-web: 10 phần, Netlify deploy, dark theme",description:"Chuyển đổi giáo trình 1274 dòng, 10 phần thành web app TailwindCSS v4 premium. Deploy Netlify thành công.",files_changed:["_abm-output/giao-trinh-web/index.html","_abm-output/giao-trinh-web/style.css","_abm-output/giao-trinh-web/app.js"],decisions:["TailwindCSS v4 CDN — tốc độ dev","Dark mode mặc định — target CEO/professional"],evidence:"Live: https://giao-trinh-abm-workforce.netlify.app. 10 phần render.",session_id:"SESSION-003",duration:120},
    {id:"TASK-024",date:"2026-03-14",title:"Audit + Fix Giáo trình Web — P0/P1/P2",department:"Đào Tạo",agent:"Jarvis",worker:"jarvis-direct",skills:["multi-dimensional-review","web-accessibility"],status:"done",completion:100,result:"Logo, search, CTA, lazy-load, performance optimized",description:"Audit phản biện 8 personas cho giáo trình web. Fix 15 issues: P0 (logo, search, CTA), P1 (sidebar, reading time, orbs, headers), P2 (print, accessibility).",files_changed:["_abm-output/giao-trinh-web/index.html","_abm-output/giao-trinh-web/style.css","_abm-output/giao-trinh-web/_headers"],decisions:["CTA bar dẫn về abmedu.vn — conversion path","Logo từ abmedu.vn — nhất quán thương hiệu"],evidence:"15/15 issues fixed. Netlify re-deploy OK.",session_id:"SESSION-004",duration:90},
    {id:"TASK-025",date:"2026-03-14",title:"Hybrid 3-Tier Skills + Auto Setup",department:"Ban Giám Đốc",agent:"Jarvis",worker:"dev-worker",skills:["writing-plans","skill-creator"],status:"done",completion:100,result:"79 skills, setup.ps1/sh/bat, audit 9.0/10",description:"Tái cấu trúc skills thành 3 tier: Tier 1 (10 global), Tier 2 (69 local), Tier 3 (community). Tạo auto setup scripts.",files_changed:["setup.ps1","setup.sh","setup.bat","_abm/RULES_GLOBAL.md"],decisions:["3-Tier hybrid: global (symlink) + local + community","setup.ps1 hỗ trợ -Force, -Verify, -Uninstall"],evidence:"79 skills mapped. setup.ps1 -Verify PASS. Audit 9.0/10.",session_id:"SESSION-004",duration:75},
    {id:"TASK-026",date:"2026-03-14",title:"README v4.0 + GitHub Push",department:"Ban Giám Đốc",agent:"Jarvis",worker:"dev-worker",skills:["copywriting","frontend-design"],status:"done",completion:100,result:"6 mermaid diagrams, CTA, comparison table, push OK",description:"Viết lại README.md v4.0: marketing-grade copy, 6 Mermaid diagrams, bảng so sánh, 20 slash commands, contract/attestation flow.",files_changed:["README.md"],decisions:["Marketing tone thay vì technical docs","6 Mermaid diagrams cho visual appeal","CTA: Cài đặt trong 60 giây"],evidence:"git push origin main → success. README render đúng. Mermaid hiển thị.",session_id:"SESSION-004",duration:60},
    {id:"TASK-027",date:"2026-03-14",title:"Coaching 1:1 Tài Liệu — Chỉnh sửa gói 250tr",department:"Kinh Doanh",agent:"Jarvis",worker:"marketing-specialist",skills:["copywriting","high-ticket-sales"],status:"done",completion:100,result:"Tài liệu coaching restructured, pricing tối ưu",description:"Chỉnh sửa tài liệu Coaching 1:1 Platinum gói 250 triệu: restructure theo 4D Model, tối ưu pricing, thêm case studies và ROI proof.",files_changed:["_abm-output/sales/coaching-1-1-platinum.md"],decisions:["4D Model framework chính","ROI proof quan trọng hơn feature list cho high-ticket"],evidence:"Tài liệu restructured. 4D Model. Pricing tối ưu 250tr.",session_id:"SESSION-004",duration:45},
    {id:"TASK-028",date:"2026-03-14",title:"Onboarding CSKH — Kế hoạch cho khách mới",department:"CSKH",agent:"Jarvis",worker:"hr-specialist",skills:["client-success","talent-acquisition"],status:"done",completion:100,result:"Onboarding plan 30/60/90, checklist, welcome email",description:"Xây dựng kế hoạch onboarding khách mới theo mô hình 30/60/90 ngày. Checklist 15 bước, welcome email, satisfaction survey.",files_changed:["_abm-output/cskh/onboarding-plan.md","_abm-output/cskh/welcome-email.md"],decisions:["30/60/90 model thay vì 7-ngày — phù hợp high-ticket","15-bước checklist cover welcome → first-value → retention"],evidence:"Onboarding plan 30/60/90 hoàn chỉnh. Checklist 15 bước. Welcome email ready.",session_id:"SESSION-004",duration:45}
];

// Workspace stats — v4.0 auto-scanned
const WORKSPACE_STATS = {
    skills: 79,
    routes: 20,
    workflows: 20,
    subagents: 5,
    workers: 5,
    departments: 11,
    version: "v4.0",
    lastSync: "2026-03-15 07:50:00"
};