# -*- coding: utf-8 -*-
"""
Premium Excel Report Builder (XlsxWriter) v3.0
Generates Enterprise-grade Excel reports from JSON data.
Implements 16 premium features including multi-level headers, column grouping, 
conditional formatting, autofit, freeze panes, zebra striping, and charts.
"""

import sys
import json
import xlsxwriter
import datetime

THEMES = {
    'ocean': {
        'primary': '#1B2A4A',
        'secondary': '#3498DB',
        'accent': '#E74C3C',
        'bg_alt': '#F0F4FA',
        'text': '#333333'
    },
    'forest': {
        'primary': '#2C3E50',
        'secondary': '#27AE60',
        'accent': '#F39C12',
        'bg_alt': '#F4FBF7',
        'text': '#333333'
    }
}

def build_excel(json_path, output_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        config = json.load(f)

    wb = xlsxwriter.Workbook(output_path)
    wb.set_properties({
        'title': config.get('report_title', 'Enterprise Report'),
        'author': config.get('author', 'ABM-Workforce Agent'),
        'comments': 'Generated by Python Excel Pro Skill v3.0'
    })

    theme_name = config.get('theme', 'ocean')
    theme = THEMES.get(theme_name, THEMES['ocean'])

    # Formats
    format_title = wb.add_format({
        'bold': True, 'font_size': 20, 'font_name': 'Arial',
        'font_color': theme['primary'], 'align': 'left', 'valign': 'vcenter'
    })
    format_meta = wb.add_format({
        'italic': True, 'font_size': 9, 'font_color': '#888888', 'font_name': 'Arial'
    })
    
    # Header format
    format_header = wb.add_format({
        'bold': True, 'font_color': 'white', 'bg_color': theme['primary'],
        'border': 1, 'font_name': 'Arial', 'align': 'center', 'valign': 'vcenter', 'text_wrap': True
    })
    format_header_accent = wb.add_format({
        'bold': True, 'font_color': 'white', 'bg_color': theme['secondary'],
        'border': 1, 'font_name': 'Arial', 'align': 'center', 'valign': 'vcenter', 'text_wrap': True
    })
    # Top-level group header format
    format_group_header = wb.add_format({
        'bold': True, 'font_size': 12, 'font_color': 'white', 'bg_color': '#34495E',
        'border': 1, 'font_name': 'Arial', 'align': 'center', 'valign': 'vcenter'
    })

    base_format = {'font_name': 'Arial', 'font_size': 11, 'border': 1, 'valign': 'vcenter'}
    f_string = wb.add_format(base_format)
    f_int = wb.add_format({**base_format, 'num_format': '#,##0'})
    f_float = wb.add_format({**base_format, 'num_format': '#,##0.00'})
    f_currency = wb.add_format({**base_format, 'num_format': '_(* #,##0.00_);_(* (#,##0.00);_(* "-"??_);_(@_)'})
    f_currency_vnd = wb.add_format({**base_format, 'num_format': '_(* #,##0_);_(* (#,##0);_(* "-"??_);_(@_)'})
    f_date = wb.add_format({**base_format, 'num_format': 'dd/mm/yyyy', 'align': 'center'})

    type_formats = {
        'string': f_string, 'int': f_int, 'float': f_float,
        'currency': f_currency_vnd, 'date': f_date
    }

    f_total_currency = wb.add_format({
        **base_format, 'bold': True, 'num_format': '_(* #,##0_);_(* (#,##0);_(* "-"??_);_(@_)',
        'top': 2, 'bg_color': '#EFEFEF'
    })
    f_total_int = wb.add_format({
        **base_format, 'bold': True, 'num_format': '#,##0',
        'top': 2, 'bg_color': '#EFEFEF'
    })
    f_total_text = wb.add_format({
        **base_format, 'bold': True, 'align': 'right', 'top': 2, 'bg_color': '#EFEFEF'
    })

    for table in config.get('tables', []):
        sheet_name = table.get('sheet_name', 'Data')
        ws = wb.add_worksheet(sheet_name)
        
        # Clean UI: Ignore Number Stored As Text globally for A1 to ZZ1048576
        ws.ignore_errors({'number_stored_as_text': 'A1:XFD1048576'})

        ws.set_landscape()
        ws.fit_to_pages(1, 0)
        ws.hide_gridlines(2)

        ws.write(0, 0, config.get('report_title', 'Report'), format_title)
        ws.write(1, 0, f"Generated exactly at: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Author: {config.get('author', 'System')}", format_meta)

        headers = table.get('headers', [])
        types = table.get('types', ['string'] * len(headers))
        data = table.get('data', [])
        groups = table.get('column_groups', [])
        
        row_start = 3
        data_start_row = row_start + 1
        
        # Multi-level Headers & Grouping
        if groups: # V3 Feature
            data_start_row = row_start + 2
            current_col = 0
            for grp in groups:
                span = grp.get('span', 1)
                title = grp.get('title', '')
                collapsed = grp.get('collapsed', False)
                end_col = current_col + span - 1
                
                if span > 1:
                    ws.merge_range(row_start, current_col, row_start, end_col, title, format_group_header)
                else:
                    ws.write(row_start, current_col, title, format_group_header)
                
                # Setup Column Outline (Group)
                if span > 1:
                    # Group columns (excel outline), keep first column of group visible if collapsed
                    ws.set_column(current_col + 1, end_col, None, None, {'level': 1, 'hidden': collapsed})
                
                current_col += span
            
            # Write child headers on row_start + 1
            for col_idx, header in enumerate(headers):
                fmt = format_header_accent if types[col_idx] in ['currency', 'int', 'float'] else format_header
                ws.write(row_start + 1, col_idx, header, fmt)
            
            # Freeze panes at data start
            ws.freeze_panes(data_start_row, 1)
            # Auto-filter
            if len(data) > 0:
                ws.autofilter(row_start + 1, 0, data_start_row + len(data) - 1, len(headers) - 1)
                
        else: # Standard V2 headers
            for col_idx, header in enumerate(headers):
                fmt = format_header_accent if types[col_idx] in ['currency', 'int', 'float'] else format_header
                ws.write(row_start, col_idx, header, fmt)
            ws.freeze_panes(data_start_row, 1)
            if headers and len(data) > 0:
                ws.autofilter(row_start, 0, data_start_row + len(data) - 1, len(headers) - 1)

        col_widths = [max(len(str(h)), 10) for h in headers]

        # Write Data
        for ri, row_data in enumerate(data):
            r = data_start_row + ri
            for ci, cell_value in enumerate(row_data):
                content_len = len(str(cell_value)) + (4 if types[ci] == 'currency' else 0)
                if content_len > col_widths[ci]:
                    col_widths[ci] = min(content_len, 50) 
                
                fmt = type_formats.get(types[ci], f_string)
                if types[ci] == 'date' and isinstance(cell_value, str):
                    try:
                        dt = datetime.datetime.strptime(cell_value, '%Y-%m-%d')
                        ws.write_datetime(r, ci, dt, fmt)
                        continue
                    except: pass
                ws.write(r, ci, cell_value, fmt)

        # Zebra striping
        ws.conditional_format(data_start_row, 0, data_start_row + len(data) - 1, len(headers) - 1, {
            'type': 'formula',
            'criteria': '=MOD(ROW(),2)=0',
            'format': wb.add_format({'bg_color': theme['bg_alt']})
        })
        
        # V3 Conditional Formats
        cond_formats = table.get('conditional_formats', [])
        for cf in cond_formats:
            col_idx = cf.get('col')
            cf_type = cf.get('type')
            if col_idx is not None and cf_type == 'data_bar':
                ws.conditional_format(data_start_row, col_idx, data_start_row + len(data) - 1, col_idx, {
                    'type': 'data_bar',
                    'bar_color': cf.get('bar_color', theme['secondary'])
                })
            elif col_idx is not None and cf_type == '3_color_scale':
                ws.conditional_format(data_start_row, col_idx, data_start_row + len(data) - 1, col_idx, {
                    'type': '3_color_scale',
                    'min_color': cf.get('min_color', '#27AE60'), # Green
                    'mid_color': cf.get('mid_color', '#F1C40F'), # Yellow
                    'max_color': cf.get('max_color', '#E74C3C')  # Red
                })

        for ci, width in enumerate(col_widths):
            # If not already overriding set_column (from groups), we should ideally not override the level/hidden flags.
            # However, xlsxwriter allows updating width without erasing level if we only pass width.
            # But we must be careful. `set_column` overwrites.
            # Actually, we already set level and hidden. Calling set_column again will merge properties!
            ws.set_column(ci, ci, width + 2)

        ws.repeat_rows(row_start, data_start_row - 1)

        end_row = data_start_row + len(data) - 1
        if table.get('totals_row') and data:
            ws.write(end_row + 1, 0, 'TỔNG CỘNG', f_total_text)
            for ci in range(1, len(headers)):
                if types[ci] == 'currency':
                    ws.write_formula(end_row + 1, ci, f'=SUM({xlsxwriter.utility.xl_rowcol_to_cell(data_start_row, ci)}:{xlsxwriter.utility.xl_rowcol_to_cell(end_row, ci)})', f_total_currency)
                elif types[ci] == 'int' or types[ci] == 'float':
                    ws.write_formula(end_row + 1, ci, f'=SUM({xlsxwriter.utility.xl_rowcol_to_cell(data_start_row, ci)}:{xlsxwriter.utility.xl_rowcol_to_cell(end_row, ci)})', f_total_int)
                else:
                    ws.write(end_row + 1, ci, '', f_total_text)

        chart_cfg = table.get('chart')
        if chart_cfg and data:
            chart = wb.add_chart({'type': chart_cfg.get('type', 'column')})
            cat_col = chart_cfg.get('category_col', 0)
            val_col = chart_cfg.get('value_col', 1)

            cat_range = [sheet_name, data_start_row, cat_col, end_row, cat_col]
            val_range = [sheet_name, data_start_row, val_col, end_row, val_col]

            chart.add_series({
                'name':       [sheet_name, data_start_row - 1, val_col],
                'categories': cat_range,
                'values':     val_range,
                'fill':       {'color': theme['secondary']},
                'border':     {'color': theme['primary']}
            })

            chart.set_title({'name': chart_cfg.get('title', 'Chart')})
            chart.set_legend({'position': 'bottom'})
            chart.set_x_axis({'name': headers[cat_col]})
            chart.set_y_axis({'name': headers[val_col], 'major_gridlines': {'visible': True}})
            chart.set_style(11)

            ws.insert_chart(row_start, len(headers) + 2, chart, {'x_offset': 15, 'y_offset': 10})

    wb.close()
    print(f">> OK: Successfully generated premium Excel report at: {output_path}")

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: python build_excel.py <data.json> <output.xlsx>")
        sys.exit(1)
    build_excel(sys.argv[1], sys.argv[2])
